### ISSUE TITLE
Funzioni prototipali

### ISSUE THREAD

**Issue by Pallalallo** [AnalistaProgrammatore/esercizi-javascript-07-04-Pallalallo#1]
Negli esercizi sullo stack non usa le funzioni pop e push che ho dichiarato ma quelle di javascript.

**Comment by nonno-cicala** [comment]
Chiami le funzioni pop e push come metodi di this.dataStore, che è un Array e non un'istanza di ParCheck.
Poiché `this` all'interno della classe è un'istanza di ParCheck per usare i metodi della classe all'interno della classe stessa puoi scrivere `this.pop()` e `this.push()`. Correggi tenendo in considerazione che la proprietà `length` di dataStore non restituirà più la lunghezza dello stack, per come operano i pop e push che hai definito nella classe, e dovrai pertanto usare anche il tuo metodo `length()`.

Buon lavoro :slightly_smiling_face:

**Comment by Pallalallo** [comment]
Ah ho capito, grazie!

**Comment by nonno-cicala** [comment]
> Ah ho capito, grazie!

Allora magari correggi e fai il push delle modifiche :slightly_smiling_face:

**Comment by Pallalallo** [comment]
Ecco fatto, dovrebbero essere corretti

**Comment by nonno-cicala** [comment]
Bene! Anche se mi sembra ti sia dimenticato un `dataStore` di troppo alla [riga 32](https://github.com/AnalistaProgrammatore/esercizi-javascript-07-04-Pallalallo/blob/4740ccaf9ff06b0d55695296a4c5ed04a184cd3d/stack/Parantesi.js#L32) :slightly_smiling_face:
